### PR TITLE
Don't set Set-Cookie header when req.session.cookie is undefined

### PR DESCRIPTION
**Pull request by cilphex**
Line 118: Currently, the cookie header is set even if `req.session.cookie` is undefined. When `cookie.serialize` is called, it returns some value that is missing a `path=<path>` part, since obviously it can't pull it from an undefined value. This PR fixes(?) that by simply not setting the cookie header if `req.session.cookie` is undefined.

### CODE REVIEW

**Comment by cilphex** [comment]
I don't know if this is the perfect fix because I don't understand cookie & session management well enough, it's quite complicated, but this works for us locally.

**Comment by cilphex** [comment]
UPDATE: I have changed the code. Instead of not setting the cookie header when `req.session.cookie` is undefined, it will set the header to the serialized value of `cookie_opt` instead of `req.session.cookie`. `cookie_opt` will be set to `req.session.cookie` when it's present, and the specified `cookie_options` otherwise - and those `cookie_options` will have the path.

**Comment by defunctzombie** [comment]
@cilphex please add a test and squash commits.

Why do you think setting to cookie_opts is better than not setting at all?

**Comment by cilphex** [comment]
I'm not sure, maybe you can tell me which you think is better. Tests failed on the first commit, they fail on the 2nd. I figure if the code wants to set something, let it, but it should respect the params, which is what the 2nd commit does.

**Comment by defunctzombie** [comment]
I'll look over it and see what makes sense. Could you still add a test that would have failed with the previous code/behavior; it seems like you were able to describe and reproduce the issue so a test showing previous failure would be good to ensure no regressions in the future.

**Comment by cilphex** [comment]
Yeah, trying to understand the tests right now.

**Comment by cilphex** [comment]
Finding it difficult to figure out how to write a test for this case.

**Comment by defunctzombie** [comment]
@cilphex wasn't the issue that it tried to set a cookie value using options that were undefined? I'll take a crack at it over the weekend if I can find some time :)

**Comment by defunctzombie** [comment]
The issue was exposed when you do `res.session = {}` instead of using the `reset()` function. I have fixed it in a manner similar to yours in https://github.com/defunctzombie/node-yummy/commit/0a7ab09ef022e5549409a731d37237d7fed9cd72

**Comment by cilphex** [comment]
This fix does work for us, but we are using `reset` instead of setting the session manually:

```
app.get('/signout', function(req, res, next) {
    req.session.reset();
    res.render('signout');
});
```

Might have something to do with the redirects that happen after hitting that path, some kind of unexpected race condition.

Thanks for your help, appreciate the fix.

**Comment by defunctzombie** [comment]
Gotcha, well, if you do end up being able to reproduce a race condition a test with that might be nice too; or at least understanding what is going on might be educational.

**Pull request closed without merging**
